### ISSUE TITLE
Void member function should not return a value from array manipulations

### ISSUE THREAD

**Issue by mnlrsn** [SerenityOS/jakt#191] opened 2022-05-21 15:48 UTC
The void member function quoted below is building an array intended to initialize a member variable. It is transpiled to C++ code that includes the TRY macro, thereby implicitly returning a value.  This generated an error message when compiling the generated C++ code.

Reduced test case (leaving aside that it probably would produce a runtime error violating array boundaries):

```
class Row {
    entries: [u16]
}

class Test {
    rows: [Row]

    function init(mutable this, dims: u8)  {
        for i in 0..(dims-1) {
            let entries = [0u16; 2]
            this.rows[i] = Row(entries: entries)
        }
    }
}
```
`$ ../../jakt/target/debug/jakt Test.jakt &&  clang++ -std=c++20 -I ../../jakt/ -I ../../jakt/runtime/  -Wno-user-defined-literals output.cpp`

```
output.cpp:32:41: error: void function 'init' should not return a value [-Wreturn-type]
            const Array<u16> entries = (TRY(Array<u16>::filled(static_cast<i64>(2LL), static_cast<u16>(0))));
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../jakt/runtime/AK/Try.h:16:13: note: expanded from macro 'TRY'
            return _temporary_result.release_error(); \
            ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
output.cpp:33:38: error: void function 'init' should not return a value [-Wreturn-type]
            (((((this)->rows))[i]) = TRY(Row::create(entries)));
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
../../jakt/runtime/AK/Try.h:16:13: note: expanded from macro 'TRY'
            return _temporary_result.release_error(); \
            ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by linusg** [comment] 2022-05-21 15:55
Duplicate of #137.

**Closed by linusg** 2022-05-21 15:55 UTC
